FROM nginx:stable-alpine
MAINTAINER Christophe Furmaniak <christophe.furmaniak@gmail.com>

LABEL LOOZ_VERSION=v0.0.8-hack

COPY src/main/config/nginx-base-with-rancher-dns-hack.conf /etc/nginx/nginx.conf
COPY src/main/html/* /etc/nginx/html/
