---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    product: guestbook
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        product: guestbook
    spec:
      containers:
      - name: frontend
        image: looztra/guestbook-simple-frontend:0.5.0-confd
        ports:
        - containerPort: 80
        env:
        - name: GUESTBOOK_FRONTEND_API_SERVER_ROOT_URL
          value: "http://gateway-myproject.192.168.99.103.xip.io"
